### PR TITLE
Railo compatibility fixes and more new features

### PR DESCRIPTION
**Pull request by lmajano**
Added several railo strict scope compatibility fixes and also added capabilities for
afterTests() and beforeTests().

### CODE REVIEW

**Comment by bennadel** [comment]
@lmajano Oh snap, sorry for not getting back to you sooner! I only just saw this notification (via the blue-dot at the top of the page -- I didn't even know what that dot was). And for some reason, I never got email notifications for this stuff.

Hmmm, and now I have to figure out how to actually handle pull-requests! I've done a lot of committing to GitHub... but _never_ done anything else with it :D 

I'll figure this out in the morning. Thanks!

**Comment by bennadel** [comment]
@lmajano Can you just clarify the "strict scope" stuff? Does Railo not implicitly look in the arguments scope? Or is this a setting that can be toggled in the Railo admin?

**Comment by lmajano** [comment]
You are right, I left a typo there, sorry. 

The strict stuff is a setting in Railo.

**Comment by bennadel** [comment]
@lmajano Thanks for the updates. I pulled them down, tweaked them a little bit (for personal style) and merged. You rock!!

**Pull request merged**
